[tox]
envlist =
    py3{10-14}-dj52-{sqlite3,postgres,mysql,mariadb},
    py3{12-14}-dj{60,61,main}-{sqlite3,postgres,mysql,mariadb},
    docs,
    lint

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314, docs, lint

[gh-actions:env]
DJANGO =
    5.2: dj52
    6.0: dj60
    6.1: dj61
    main: djmain

[flake8]
ignore = N802,F401,W503
max-complexity = 10
max-line-length = 88
exclude = __init__.py,simple_history/registry_tests/migration_test_app/migrations/*

[testenv]
deps =
    -rrequirements/test.txt
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1
    dj61: Django>=6.1a,<6.2
    djmain: https://github.com/django/django/tarball/main
    postgres: -rrequirements/postgres.txt
    mysql: -rrequirements/mysql.txt
    mariadb: -rrequirements/mysql.txt

commands =
    sqlite3: coverage run -a runtests.py {posargs}
    postgres: coverage run -a runtests.py --database=postgres {posargs}
    mysql: coverage run -a runtests.py --database=mysql {posargs}
    mariadb: coverage run -a runtests.py --database=mariadb {posargs}
    coverage report

[testenv:format]
deps = -rrequirements/lint.txt
commands =
    isort docs simple_history runtests.py
    black docs simple_history runtests.py
    flake8 simple_history

[testenv:lint]
deps = pre-commit
commands =
    pre-commit run --all-files

[testenv:docs]
changedir = docs
deps = -rrequirements/docs.txt
commands = sphinx-build -W -b html -d {envtmpdir}/doctrees . {envtmpdir}/html
